import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn} from "@clerk/nextjs";
import Header from "@/components/header";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="bg-gradient-to-b from-[#2C2C3E] to-[#1E1E2E]">
        {/* <body className="bg-gradient-to-br from-[#0A192F] to-[#00498D]"> */}
          <header >
            <SignedIn>
              <Header/>
            </SignedIn>
          </header>
          <main >{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
